### ISSUE TITLE
this works fine on 1.18, change version?

### ISSUE THREAD

**Issue by j0lol** [InfiniteImperm/fabric-hide-bossbar#1]
i just compiled it on 1.18 and it seems to work fine :) thanks for mod

**Comment by InfiniteImperm** [comment]
Hello there, I didn't test it yet on 1.18 but I plan to in the future. If you have any problems or find bugs please don't hesitate to contact me. Have fun with the mod in the meantime (:

**Comment by j0lol** [comment]
should probably close this :p gonna test on 1.19.2 :)
